name: Go
on: [push, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v2
        with:
          dest: dist
          targets: windows/386,windows/amd64,darwin/arm64,darwin/amd64,linux/386,linux/amd64,linux/arm64,linux/mips64,linux/mips64le
          v: true
          x: false
          ldflags: -s -w

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DDatHome-go
          path: dist
