name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v2
        with:
          dest: build
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64,linux/arm64,linux/mips64,linux/mips64le
          v: true
          x: false
          ldflags: -s -w

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
